2023-05-26 12:58:04,151 [INFO] Watching for file changes with StatReloader
2023-05-26 12:58:57,313 [INFO] /home/claudio/projetos/psych/psych/urls.py changed, reloading.
2023-05-26 12:58:57,477 [INFO] Watching for file changes with StatReloader
2023-05-26 12:59:43,619 [INFO] /home/claudio/projetos/psych/psych/urls.py changed, reloading.
2023-05-26 12:59:43,769 [INFO] Watching for file changes with StatReloader
2023-05-26 13:07:48,870 [INFO] Watching for file changes with StatReloader
2023-05-26 13:09:27,786 [INFO] Watching for file changes with StatReloader
2023-05-26 13:11:17,094 [INFO] Watching for file changes with StatReloader
2023-05-26 13:15:43,809 [INFO] /home/claudio/projetos/psych/psych/views.py changed, reloading.
2023-05-26 13:15:43,958 [INFO] Watching for file changes with StatReloader
2023-05-26 13:16:28,101 [INFO] /home/claudio/projetos/psych/psych/views.py changed, reloading.
2023-05-26 13:16:28,248 [INFO] Watching for file changes with StatReloader
2023-05-26 13:17:56,716 [INFO] Watching for file changes with StatReloader
2023-05-26 13:18:39,854 [INFO] /home/claudio/projetos/psych/psych/urls.py changed, reloading.
2023-05-26 13:18:40,021 [INFO] Watching for file changes with StatReloader
2023-05-26 13:18:50,179 [INFO] Watching for file changes with StatReloader
2023-05-26 13:21:03,563 [INFO] /home/claudio/projetos/psych/psych/urls.py changed, reloading.
2023-05-26 13:21:03,711 [INFO] Watching for file changes with StatReloader
2023-05-26 13:21:42,837 [INFO] /home/claudio/projetos/psych/psych/urls.py changed, reloading.
2023-05-26 13:21:42,981 [INFO] Watching for file changes with StatReloader
2023-05-26 13:21:46,017 [INFO] /home/claudio/projetos/psych/psych/urls.py changed, reloading.
2023-05-26 13:21:46,169 [INFO] Watching for file changes with StatReloader
2023-05-26 13:21:53,218 [INFO] Watching for file changes with StatReloader
2023-05-26 13:22:46,174 [INFO] Watching for file changes with StatReloader
2023-05-26 13:23:22,475 [INFO] Watching for file changes with StatReloader
2023-05-26 13:26:24,984 [INFO] /home/claudio/projetos/psych/psych/urls.py changed, reloading.
2023-05-26 13:26:25,129 [INFO] Watching for file changes with StatReloader
2023-05-26 13:30:57,834 [INFO] /home/claudio/projetos/psych/psych/urls.py changed, reloading.
2023-05-26 13:30:57,983 [INFO] Watching for file changes with StatReloader
2023-05-26 13:31:39,107 [INFO] /home/claudio/projetos/psych/psych/urls.py changed, reloading.
2023-05-26 13:31:39,252 [INFO] Watching for file changes with StatReloader
2023-05-26 13:31:43,296 [INFO] /home/claudio/projetos/psych/psych/urls.py changed, reloading.
2023-05-26 13:31:43,452 [INFO] Watching for file changes with StatReloader
2023-05-26 13:33:21,715 [INFO] /home/claudio/projetos/psych/psych/urls.py changed, reloading.
2023-05-26 13:33:21,865 [INFO] Watching for file changes with StatReloader
2023-05-26 13:34:42,093 [INFO] /home/claudio/projetos/psych/psych/urls.py changed, reloading.
2023-05-26 13:34:42,236 [INFO] Watching for file changes with StatReloader
2023-05-26 13:35:10,371 [INFO] /home/claudio/projetos/psych/psych/settings.py changed, reloading.
2023-05-26 13:35:10,521 [INFO] Watching for file changes with StatReloader
2023-05-26 13:35:15,532 [ERROR] Internal Server Error: /
Traceback (most recent call last):
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/claudio/projetos/psych/psych/views.py", line 12, in dashboard
    return render(request, template_path, {'config': config})
  File "/home/claudio/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: templates/psych/dashboard.html
2023-05-26 13:40:16,527 [INFO] /home/claudio/projetos/psych/psych/settings.py changed, reloading.
2023-05-26 13:40:16,675 [INFO] Watching for file changes with StatReloader
2023-05-26 13:40:20,920 [ERROR] Internal Server Error: /
Traceback (most recent call last):
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/claudio/projetos/psych/psych/views.py", line 12, in dashboard
    return render(request, template_path, {'config': config})
  File "/home/claudio/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: templates/psych/dashboard.html
2023-05-26 13:43:48,613 [INFO] /home/claudio/projetos/psych/psych/views.py changed, reloading.
2023-05-26 13:43:48,770 [INFO] Watching for file changes with StatReloader
2023-05-26 13:44:02,880 [INFO] /home/claudio/projetos/psych/psych/views.py changed, reloading.
2023-05-26 13:44:03,036 [INFO] Watching for file changes with StatReloader
2023-05-26 13:44:19,155 [INFO] /home/claudio/projetos/psych/clientes/views.py changed, reloading.
2023-05-26 13:44:19,328 [INFO] Watching for file changes with StatReloader
2023-05-26 13:44:24,209 [ERROR] Internal Server Error: /
Traceback (most recent call last):
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/claudio/projetos/psych/psych/views.py", line 11, in dashboard
    return render(request, 'psych/dashboard.html', {'config': config})
  File "/home/claudio/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: psych/dashboard.html
2023-05-26 13:45:00,578 [INFO] /home/claudio/projetos/psych/psych/views.py changed, reloading.
2023-05-26 13:45:00,736 [INFO] Watching for file changes with StatReloader
2023-05-26 13:45:11,497 [ERROR] Internal Server Error: /clientes/
Traceback (most recent call last):
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/claudio/projetos/psych/clientes/views.py", line 9, in index
    return render(request, 'index.html', context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
2023-05-26 13:45:15,278 [ERROR] Internal Server Error: /clientes/
Traceback (most recent call last):
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/claudio/projetos/psych/clientes/views.py", line 9, in index
    return render(request, 'index.html', context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
2023-05-26 13:48:12,402 [ERROR] Internal Server Error: /clientes/
Traceback (most recent call last):
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: psych/base/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/claudio/projetos/psych/clientes/views.py", line 9, in index
    return render(request, 'index.html', context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: psych/base/default.html
2023-05-26 13:48:13,938 [ERROR] Internal Server Error: /clientes/
Traceback (most recent call last):
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: psych/base/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/claudio/projetos/psych/clientes/views.py", line 9, in index
    return render(request, 'index.html', context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: psych/base/default.html
2023-05-27 19:09:58,999 [INFO] Watching for file changes with StatReloader
2023-05-27 19:12:24,299 [INFO] Watching for file changes with StatReloader
2023-05-27 19:13:41,335 [INFO] Watching for file changes with StatReloader
2023-05-27 19:15:07,550 [INFO] /home/claudio/projetos/psych/clientes/views.py changed, reloading.
2023-05-27 19:15:08,126 [INFO] Watching for file changes with StatReloader
2023-06-02 18:16:45,629 [INFO] Watching for file changes with StatReloader
2023-06-02 18:18:04,745 [INFO] /home/claudio/projetos/psych/psych/settings.py changed, reloading.
2023-06-02 18:18:05,242 [INFO] Watching for file changes with StatReloader
2023-06-02 18:18:06,730 [ERROR] Internal Server Error: /clientes/
Traceback (most recent call last):
  File "/home/claudio/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: clientes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/claudio/projetos/psych/clientes/views.py", line 12, in index
    return render(request, 'index.html', context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 194, in render
    len_values = len(values)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/claudio/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/claudio/.local/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/claudio/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/claudio/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/claudio/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/claudio/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/claudio/.local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: clientes
2023-06-02 18:28:01,077 [WARNING] Not Found: /favicon.ico
2023-06-02 18:28:57,078 [WARNING] Not Found: /favicon.ico
2023-06-02 18:32:33,753 [WARNING] Not Found: /favicon.ico
2023-06-02 18:34:34,572 [WARNING] Not Found: /favicon.ico
